// Optional DOM harness: BIG_TWO_DOM_PATH points to an installed linkedom package entry.
// This exercises React behavior, not browser layout or device rendering.
import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {build} from 'esbuild';
import React,{act} from 'react';
import {POST} from '../app/api/big-two/route.ts';
import {chooseBotMove} from '../app/big-two/engine.ts';
test('React room flow: create, join, ready with lost response, deal, play and resume same hand',{skip:!process.env.BIG_TWO_DOM_PATH},async()=>{
 const {parseHTML}=await import(process.env.BIG_TWO_DOM_PATH);const {window}=parseHTML('<html><body><div id="app"></div></body></html>');
 const storage=new Map();Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Event:window.Event,location:new URL('https://test.local/big-two'),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},matchMedia:()=>({matches:true,addEventListener(){},removeEventListener(){}}),IS_REACT_ACT_ENVIRONMENT:true});
 window.HTMLElement.prototype.showModal=function(){this.open=true;};window.HTMLElement.prototype.close=function(){this.open=false;};
 const {createRoot}=await import('react-dom/client');
 await build({entryPoints:[resolve('app/big-two/multiplayer.tsx')],bundle:true,write:true,outfile:resolve('.sites-runtime/big-two-client-test.mjs'),format:'esm',platform:'node',jsx:'automatic',loader:{'.css':'empty'},plugins:[{name:'test-imports',setup(b){b.onResolve({filter:/^react(\/.*)?$/},args=>({path:resolve('node_modules',args.path==='react/jsx-runtime'?'react/jsx-runtime.js':'react/index.js'),external:true}));b.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:"import React from 'react';export default function Link(p){return React.createElement('a',p,p.children)}"}));}}]});
 const {default:Multiplayer}=await import(resolve('.sites-runtime/big-two-client-test.mjs'));
 const database=new DatabaseSync(':memory:');database.exec(readFileSync('drizzle/0007_brown_hammerhead.sql','utf8'));
 const wrap=(sql,params)=>({async first(){return database.prepare(sql).get(...params)||null},async run(){return {meta:{changes:Number(database.prepare(sql).run(...params).changes)}}}});
 globalThis.__TEKAD_DB__={prepare(sql){return {bind(...p){return wrap(sql,p)},...wrap(sql,[])}}};
 let lost=false,loseReady=false,lostKind='ready';const bodies=[];
 globalThis.fetch=async(url,options)=>{const b=JSON.parse(options.body);bodies.push(b);const r=await POST(new Request(`https://test.local${url}`,{...options,headers:{...options.headers,Origin:'https://test.local'}}));if(loseReady&&b.type===lostKind&&!lost){lost=true;throw new Error('lost response');}return r;};
 const api=async(b)=>{const r=await POST(new Request('https://test.local/api/big-two',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),...b})}));const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));return value.room;};
 const props=el=>el[Object.keys(el).find(k=>k.startsWith('__reactProps$'))];
 const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===text);
 const wait=async(ms=20)=>act(async()=>{await new Promise(r=>setTimeout(r,ms));});
 const click=async(el)=>{assert.ok(el,'button exists');assert.ok(!el.disabled,el.textContent);await act(async()=>{props(el).onClick?.({preventDefault(){}});await new Promise(r=>setTimeout(r,20));});};
 let root=createRoot(document.getElementById('app'));await act(async()=>root.render(React.createElement(Multiplayer,{onBack(){}})));await wait();
 const input=document.querySelector('input[name="playerName"]');await act(async()=>props(input).onChange({target:{value:'Dax'}}));
 await act(async()=>{props(document.querySelector('form')).onSubmit({preventDefault(){}});await new Promise(r=>setTimeout(r,30));});
 let saved=JSON.parse(storage.get('tekad-big-two-room-v1'));assert.equal(saved.joined,true);assert.match(saved.code,/^[A-Z2-9]{6}$/);assert.match(document.body.textContent,/Meja bersama/);
 const keys=[saved.token,...['b','c','d'].map(x=>x.repeat(64))];
 for(let i=1;i<4;i++)await api({type:'join',code:saved.code,token:keys[i],name:`Friend ${i}`,character:i});await wait(1600);
 assert.equal(document.querySelectorAll('.b2-room-seat.occupied').length,4);
 loseReady=true;await click(button('Saya siap'));assert.equal(lost,true);assert.ok(button('Coba lagi'));const revision=database.prepare('SELECT revision FROM big_two_rooms WHERE code=?').get(saved.code).revision;
 assert.equal(JSON.parse(storage.get('tekad-big-two-room-v1')).pendingRequest.type,'ready');
 await act(async()=>root.unmount());root=createRoot(document.getElementById('app'));
 await act(async()=>root.render(React.createElement(Multiplayer,{onBack(){}})));await wait(80);
 assert.ok(button('Coba lagi'),'uncertain action survives refresh');
 await click(button('Coba lagi'));assert.equal(database.prepare('SELECT revision FROM big_two_rooms WHERE code=?').get(saved.code).revision,revision);assert.equal(bodies.filter(b=>b.type==='ready')[0].requestId,bodies.filter(b=>b.type==='ready')[1].requestId);
 assert.equal(JSON.parse(storage.get('tekad-big-two-room-v1')).pendingRequest,undefined,'confirmed outbox is cleared');
 for(let i=1;i<4;i++){const v=await api({type:'sync',code:saved.code,token:keys[i]});await api({type:'ready',ready:true,revision:v.revision,code:saved.code,token:keys[i]});}await wait(1600);
 await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('Bagikan kartu')));await wait(400);
 assert.equal(document.querySelectorAll('.b2-hand .b2-card').length,13);assert.equal(document.querySelectorAll('.b2-opponent').length,3);assert.ok(!document.querySelector('.b2-opponent-status').textContent.includes('BOT'));
 let v=await api({type:'sync',code:saved.code,token:keys[0]});
 for(let attempts=0;v.game.turn!==0&&attempts<4;attempts++){const seat=v.game.turn,a=await api({type:'sync',code:saved.code,token:keys[seat]});const cards=chooseBotMove(a.game.hand,a.game.table,a.game.opening,a.game.counts.filter((_,i)=>i!==seat));v=await api({type:'play',cards,revision:a.revision,code:saved.code,token:keys[seat]});}
 await wait(1600);assert.equal(v.game.turn,0);await click(button('Saran'));const selected=document.querySelectorAll('.b2-hand .b2-card[aria-pressed="true"]').length;
 lost=false;lostKind='play';
 if(selected)await click([...document.querySelectorAll('button')].find(b=>b.textContent.startsWith('Banting')));else await click(button('Pass'));
 const after=await api({type:'sync',code:saved.code,token:keys[0]});assert.equal(after.game.sequence,v.game.sequence+1);
 await act(async()=>root.unmount());root=createRoot(document.getElementById('app'));await act(async()=>root.render(React.createElement(Multiplayer,{onBack(){}})));await wait(80);
 assert.equal(JSON.parse(storage.get('tekad-big-two-room-v1')).token,saved.token);assert.equal(document.querySelectorAll('.b2-hand .b2-card').length,after.game.hand.length);assert.ok(document.querySelector('.b2-room-strip').textContent.includes(saved.code));
 assert.ok(button('Coba lagi'),'lost play can be recovered after reload');
 await click(button('Coba lagi'));
 assert.equal((await api({type:'sync',code:saved.code,token:keys[0]})).game.sequence,after.game.sequence,'reloaded retry does not play twice');
 const sentPlays=bodies.filter(b=>b.type==='play');assert.equal(sentPlays[0].requestId,sentPlays[1].requestId);
 await act(async()=>root.unmount());
 // Join from an invitation while a different saved room exists; do not silently resume the old room.
 const other=await api({type:'create',token:'e'.repeat(64),name:'Other host',character:0});globalThis.location=new URL(`https://test.local/big-two?room=${other.code}`);
 root=createRoot(document.getElementById('app'));await act(async()=>root.render(React.createElement(Multiplayer,{onBack(){}})));await wait();
 assert.ok(button('Lanjutkan room sebelumnya'));assert.equal(document.querySelector('input[name="roomCode"]').value,other.code);
 await act(async()=>{props(document.querySelector('form')).onSubmit({preventDefault(){}});await new Promise(r=>setTimeout(r,30));});await wait(60);
 assert.match(document.body.textContent,/Meja bersama/);assert.ok(!document.body.textContent.includes('Kursi tidak tersedia'));const joined=JSON.parse(storage.get('tekad-big-two-room-v1'));assert.equal(joined.code,other.code);assert.notEqual(joined.token,saved.token);assert.equal(document.querySelectorAll('.b2-room-seat.occupied').length,2);
 lost=false;lostKind='leave';
 await click(button('Keluar dari room'));await click(button('Ya, lanjutkan'));
 assert.equal(JSON.parse(storage.get('tekad-big-two-room-v1')).pendingRequest.type,'leave');
 await act(async()=>root.unmount());root=createRoot(document.getElementById('app'));
 await act(async()=>root.render(React.createElement(Multiplayer,{onBack(){}})));await wait(80);
 await click(button('Coba lagi'));assert.equal(storage.has('tekad-big-two-room-v1'),false,'lost leave resolves even after membership was removed');
 await act(async()=>root.unmount());
 storage.set('tekad-big-two-room-v1',JSON.stringify(saved));
 // A delayed resume response must not reopen a room after choosing another room.
 let release,requested;
 globalThis.fetch=async(url,options)=>{requested=options;return new Promise(resolve=>{release=resolve;});};
 globalThis.location=new URL('https://test.local/big-two');
 root=createRoot(document.getElementById('app'));await act(async()=>root.render(React.createElement(Multiplayer,{onBack(){}})));await wait(20);
 assert.ok(release,'resume request started');await click(button('Pilih room lain'));
 const delayed=await POST(new Request('https://test.local/api/big-two',requested));
 await act(async()=>{release(delayed);await new Promise(r=>setTimeout(r,20));});
 assert.ok(document.querySelector('form'),'room picker remains visible');assert.ok(!document.body.textContent.includes('Meja bersama'));
 assert.equal(storage.get('tekad-big-two-room-v1'),undefined);
 await act(async()=>root.unmount());database.close();
});
