import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const js=ts.transpileModule(readFileSync('app/tekad-jrpg/battle.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;
const {freshBattle,playerAction:act,nextActor:next,enemyAction:enemy,turnOrder,upcomingTurns,actionUnavailableReason:reason}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
let b=freshBattle();assert.equal(b.active,'kirana');assert.deepEqual(turnOrder(b),['kirana','timmy','guardian','dylan']);
assert.deepEqual(turnOrder({...b,speeds:{...b.speeds,dylan:99}}),['dylan','kirana','timmy','guardian']);
b=act(b,'harmony');assert.equal(upcomingTurns(b)[0],'kirana');assert.equal(act(b,'attack'),b);
b=next(b);assert.equal(b.active,'timmy');b=next(act(b,'guard'));assert.equal(b.phase,'enemy');
b=enemy(b);assert.equal(b.phase,'enemyRecovery');assert.equal(b.hp,232);assert.equal(b.harmony,1);
b=next(b);assert.equal(b.active,'dylan');b=next(act(b,'attack'));assert.equal(b.active,'kirana');assert.equal(b.round,2);
let d={...freshBattle(),active:'dylan'};assert.equal(act(d,'bash'),d);assert.equal(act(d,'heal'),d);assert.equal(act(d,'crusher').enemyDamage,72);assert.equal(act({...d,broken:true},'crusher').enemyDamage,120);assert.equal(act({...d,broken:true,harmony:1},'crusher').enemyDamage,150);assert.equal(act({...d,dylanMp:7},'crusher').phase,'player');
assert.equal(act({...d,dylanHp:100},'potion','dylan').dylanHp,200);
assert.equal(act({...d,active:'kirana',dylanHp:250},'heal','dylan').dylanHp,280);
let broken=act({...freshBattle(),active:'timmy',acted:['kirana'],armor:1},'bash');assert.equal(broken.broken,true);assert.equal(next(broken).phase,'enemy');
broken=enemy(next(broken));assert.equal(broken.breakRecovery,true);assert.equal(broken.heroDamage,0);assert.equal(broken.broken,true);
broken=next(broken);assert.equal(broken.active,'dylan');assert.equal(act(broken,'crusher').enemyDamage,120);
let recovered=enemy({...broken,phase:'enemy',round:2});assert.equal(recovered.broken,false);assert.equal(recovered.armor,3);
assert.equal(next({...freshBattle(),phase:'party',acted:['kirana'],hp:0}).phase,'enemy');
assert.equal(enemy({...freshBattle(),phase:'enemy',hp:0,kiranaHp:0,dylanHp:1}).phase,'lost');
assert.equal(act({...freshBattle(),enemyHp:1},'attack').phase,'won');
assert.equal(enemy({...freshBattle(),phase:'enemy',round:3,dylanGuard:true,harmony:1}).dylanDamage,17);
assert.match(reason({...freshBattle(),kiranaMp:0},'heal'),/Not enough MP/);
assert.match(reason(freshBattle(),'potion'),/full HP/);
assert.match(reason({...freshBattle(),potions:0},'potion'),/No potions/);
assert.equal(act({...freshBattle(),hp:208},'heal','timmy').healed,32);
b=freshBattle();for(let i=0;i<200&&!['won','lost'].includes(b.phase);i++){
 if(b.phase==='party'||b.phase==='enemyRecovery')b=next(b);else if(b.phase==='enemy')b=enemy(b);
 else if(b.active==='timmy')b=act(b,b.round%3===0?'guard':b.armor>0&&b.mp>=6?'bash':'attack');
 else if(b.active==='dylan')b=act(b,b.round%3===2?'guard':b.dylanMp>=8?'crusher':'attack');
 else b=act(b,b.hp<170&&b.kiranaMp>=8?'heal':b.round%3===0?'guard':'attack','timmy');
}assert.equal(b.phase,'won');
console.log('Speed order, mid-round enemy turns, KO skipping, Break lifecycle, healing, skill costs and complete battle passed.');
