export type ArcadeGame = {
  id: string; title: string; subtitle: string; genre: string; players: string;
  description: string; detail: string; href: string; cover: string; artwork: string;
  accent: string; position: string; mobilePosition: string; chapter?: string;
};

export const arcadeGames: ArcadeGame[] = [
  { id: 'big-two', title: 'BIG 2: Wild Cards', subtitle: 'TEKAD CARD CLUB', genre: 'Kartu', players: '4 pemain · Online / bot', description: 'Tiga lawan. Tiga belas kartu. Tentukan kapan harus menahan, dan kapan harus menghabiskan semuanya.', detail: 'Buat room bersama teman atau main melawan bot.', href: '/big-two', cover: '/arcade-home/covers/big-two.webp', artwork: '/arcade-home/big-two-hero.webp', accent: '#fb4260', position: '65% 45%', mobilePosition: '72% 35%' },
  { id: 'workshop', title: 'Eldric’s Workshop', subtitle: 'ENERGY ROUTING', genre: 'Puzzle', players: '1 pemain', description: 'Sambungkan jalur energi. Hidupkan kembali mesin-mesin di bengkel Eldric.', detail: '20 level · Ketuk untuk memutar jalur', href: '/eldrics-workshop', cover: '/arcade-home/covers/workshop.webp', artwork: '/workshop/cover.webp', accent: '#6be5db', position: '65% 45%', mobilePosition: '60% 40%' },
  { id: 'sejuta-poin', title: 'Sejuta Poin', subtitle: 'THE QUIZ SHOW', genre: 'Kuis', players: '1 pemain', description: 'Lima belas pertanyaan menuju satu juta poin. Seberapa jauh kamu bisa bertahan?', detail: 'Bantuan karakter · Papan peringkat', href: '/sejuta-poin', cover: '/arcade-home/covers/sejuta-poin.webp', artwork: '/quiz/sejuta-poin-cover.webp', accent: '#eed28b', position: '65% 40%', mobilePosition: '50% 35%' },
  { id: 'switch-run', title: 'Switch Run', subtitle: 'EARTH 3000', genre: 'Platformer', players: '1 pemain', description: 'Lari melintasi Earth 3000. Ganti karakter dan gunakan kemampuan mereka untuk melewati rintangan.', detail: 'Lima dunia · Papan peringkat', href: '/switch-run', cover: '/arcade-home/covers/switch-run.webp', artwork: '/arcade-home/switch-run-hero.webp', accent: '#b29cff', position: '65% 45%', mobilePosition: '60% 45%' },
  { id: 'saving-twilight', title: 'Saving Twilight', subtitle: 'DUSKBRIDGE', genre: 'RPG', players: '1 pemain', description: 'Jelajahi Duskbridge bersama Timmy sang Guardian. Baca serangan musuh dan pilih langkah berikutnya.', detail: 'Pertarungan bergiliran · Prolog', chapter: 'Prolog', href: '/tekad-jrpg', cover: '/arcade-home/covers/saving-twilight.webp', artwork: '/arcade-home/saving-twilight-hero.webp', accent: '#b9dfc6', position: '60% 40%', mobilePosition: '62% 35%' },
  { id: 'chronicles', title: 'TEKAD Chronicles', subtitle: 'MAHKOTA YANG RETAK', genre: 'Cerita interaktif', players: '1 pemain', description: 'Raja telah mati. Telusuri rahasia Velmora bersama lima sahabat, dengan akhir cerita yang ditentukan pilihanmu.', detail: 'Bab I · 7 keputusan · 5 akhir cerita', chapter: 'Bab I', href: '/chronicles/', cover: '/arcade-home/covers/chronicles.webp', artwork: '/arcade-home/chronicles-hero.webp', accent: '#c9b5f1', position: '65% 35%', mobilePosition: '60% 35%' },
  { id: 'racing', title: 'TEKAD Racing', subtitle: 'EARTH 3000 CIRCUIT', genre: 'Balapan', players: '1 pemain', description: 'Cari racing line terbaik. Tahan drift, lepaskan boost, dan perbaiki waktu putaranmu.', detail: 'Time trial · Versi prototipe', chapter: 'Prototipe', href: '/tekad-racing', cover: '/arcade-home/covers/racing.webp', artwork: '/arcade-home/kart-racing-hero.webp', accent: '#7cb9ff', position: '60% 40%', mobilePosition: '60% 40%' },
  { id: 'jigsaw', title: 'TEKAD Jigsaw', subtitle: 'PIECE BY PIECE', genre: 'Puzzle', players: '1 pemain', description: 'Susun potongan gambar menjadi utuh. Nikmati momen bersama TEKAD tanpa batas waktu.', detail: '60 keping · Pilihan gambar', href: '/jigsaw', cover: '/arcade-home/covers/jigsaw.webp', artwork: '/arcade-home/jigsaw-hero.webp', accent: '#efbe95', position: '65% 40%', mobilePosition: '55% 30%' },
];
