'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { HELPERS, POINTS } from './rules';
import './quiz.css';
type Question={text:string;category:string;tier:number;options:string[];removed:number[];hint:string|null;vote:number[]|null;second:boolean;retried:boolean;deadline:number;duration:number;correct?:number;explanation?:string;source?:{title:string;url?:string}};
type Game={id:string;revision:number;name:string;phase:'ready'|'active'|'review'|'ended';level:number;score:number;safe:number;elapsed:number;used:string[];serverNow:number;question:Question|null;result:{kind:string;chosen?:number}|null};
type Cue={id:number;helper:string};
type Rank={name:string;score:number;reached:number;elapsed:number};
const fmt=(n:number)=>n.toLocaleString('id-ID');
function Portrait({id}:{id:string}){const index=['timmy','eldric','kirana','adelia','dylan'].indexOf(id);return <span className="qw-portrait qw-suit-portrait" style={{backgroundImage:"url('/quiz/anime/suits-v1.png')",backgroundPosition:`${index*25}% top`}} aria-hidden="true"/>;}
export default function QuizGame(){
 const [game,setGame]=useState<Game|null>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[boot,setBoot]=useState(true),[error,setError]=useState(''),[chosen,setChosen]=useState<number|null>(null),[remaining,setRemaining]=useState(0),[ranks,setRanks]=useState<Rank[]>([]),[rankError,setRankError]=useState(''),[helper,setHelper]=useState<string|null>(null),[sound,setSound]=useState(false);
 const [cue,setCue]=useState<Cue|null>(null),[pendingAction,setPendingAction]=useState('');
 const key=useRef(''),session=useRef(''),current=useRef<Game|null>(null),locked=useRef(false),clock=useRef({server:0,local:0}),zeroSync=useRef(''),dialog=useRef<HTMLDialogElement>(null),audio=useRef<AudioContext|null>(null);
 const board=useCallback(async()=>{try{const r=await fetch('/api/quiz',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error();setRanks(d.rows);setRankError('');}catch{setRankError('Leaderboard konfirmasi koneksi diperlukan.');}},[]);
 const beep=useCallback((hz:number)=>{if(!sound)return;try{const c=audio.current||(audio.current=new AudioContext());void c.resume();const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.23);}catch{}},[sound]);
 const send=useCallback(async(type:string,extra:Record<string,unknown>={})=>{
  if(locked.current||!key.current)return;locked.current=true;setBusy(true);setPendingAction(type);setError('');
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);
  try{const response=await fetch('/api/quiz',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,key:key.current,id:session.current,revision:current.current?.revision,...extra}),signal:controller.signal});const data=await response.json();
   if(data.game){const g=data.game as Game;const previous=current.current;
    if(response.ok&&previous&&g.revision>previous.revision){const activated=g.used.find(id=>!previous.used.includes(id));if(activated)setCue({id:g.revision,helper:activated});else if(g.phase!=='active')setCue(null);}
    clock.current={server:g.serverNow,local:performance.now()};session.current=g.id;current.current=g;setGame(g);setName(g.name);setChosen(null);setHelper(null);setRemaining(g.question?Math.max(0,(g.question.deadline-g.serverNow)/1000):0);localStorage.setItem('tekad-quiz-session',g.id);if(g.phase==='ended')void board();}
   if(!response.ok){if(response.status===404){session.current='';localStorage.removeItem('tekad-quiz-session');current.current=null;setGame(null);}throw Error(data.error||'Permintaan belum berhasil.');}
  }catch(e){setError(e instanceof Error&&e.name!=='AbortError'?e.message:'Koneksi terputus. Sambungkan ulang untuk memeriksa progres. Timer tetap berjalan.');}
  finally{clearTimeout(timeout);locked.current=false;setBusy(false);setPendingAction('');setBoot(false);}
 },[board]);
 useEffect(()=>{try{let k=localStorage.getItem('tekad-quiz-key');if(!k||! /^[a-f0-9]{64}$/.test(k)){k=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(v=>v.toString(16).padStart(2,'0')).join('');localStorage.setItem('tekad-quiz-key',k);}key.current=k;session.current=localStorage.getItem('tekad-quiz-session')||'';setName(localStorage.getItem('tekad-quiz-name')||'');if(session.current)void send('sync');else setBoot(false);void board();}catch{setError('Aktifkan penyimpanan browser agar sesi dapat disimpan.');setBoot(false);}},[send,board]);
 useEffect(()=>{const onVisible=()=>{if(document.visibilityState==='visible'&&session.current)void send('sync');};document.addEventListener('visibilitychange',onVisible);window.addEventListener('online',onVisible);return()=>{document.removeEventListener('visibilitychange',onVisible);window.removeEventListener('online',onVisible);};},[send]);
 useEffect(()=>{if(game?.phase!=='active'||!game.question)return;const deadline=game.question.deadline;const tick=()=>{const left=Math.max(0,(deadline-(clock.current.server+performance.now()-clock.current.local))/1000);setRemaining(left);const marker=`${game.id}:${deadline}`;if(left===0&&zeroSync.current!==marker&&!locked.current){zeroSync.current=marker;void send('sync');}};tick();const t=setInterval(tick,100);return()=>clearInterval(t);},[game,send]);
 useEffect(()=>{if(game?.phase==='ended')dialog.current?.close();},[game?.phase]);
 useEffect(()=>{if(!cue)return;const timer=setTimeout(()=>setCue(null),4500);return()=>clearTimeout(timer);},[cue]);
 const active=game?.phase==='active',q=game?.question,done=game?.phase==='ended';const blocked=busy||!active||remaining<=0;const chosenHelper=HELPERS.find(h=>h.id===helper);const activeHelper=HELPERS.find(h=>h.id===cue?.helper);const success=game?.result?.kind==='correct'||game?.result?.kind==='win';const checkpoint=game?.phase==='review'&&(game.level===5||game.level===10);
 const helperMessages:Record<string,string>={timmy:'Dua pilihan salah disingkirkan.',eldric:'Petunjukmu sudah terbuka.',kirana:'Pendapat tim sudah tersedia.',adelia:'Soal baru, kesempatan baru.',dylan:'Kesempatan kedua sudah aktif.'};
 function start(){try{localStorage.setItem('tekad-quiz-name',name.trim());void send('start',{name});}catch{setError('Penyimpanan browser tidak tersedia.');}}
 const ladder=<ol className="qw-ladder">{POINTS.map((p,i)=><li key={p} className={`${i===4||i===9?'safe':''} ${game&&(game.phase==='active'?game.level===i:game.level-1===i)?'current':''} ${game&&i<game.level?'passed':''}`}><span>{String(i+1).padStart(2,'0')}</span><b>{fmt(p)}</b><small>{i===4||i===9?'◆':game&&i<game.level?'✓':''}</small></li>).reverse()}</ol>;
 const leaderboard=<section className="qw-board"><div className="qw-section-title"><div><span className="qw-kicker">PAPAN PRESTASI</span><h2>Peraih poin tertinggi</h2></div><button className="qw-small" onClick={()=>void board()}>Muat ulang</button></div><p>Skor terbaik tiap perangkat. Urutan: poin tertinggi, pertanyaan terjauh yang dibuka, lalu waktu menjawab tercepat.</p>{rankError?<p role="status">Belum bisa memuat leaderboard. Coba muat ulang.</p>:ranks.length?<ol>{ranks.map((r,i)=><li key={i}><span className="qw-rank">{String(i+1).padStart(2,'0')}</span><strong>{r.name}</strong><span><b>{fmt(r.score)}</b><small>Soal {r.reached} / 15 · {(r.elapsed/1000).toFixed(1)} dtk</small></span></li>)}</ol>:<div className="qw-empty">Papan prestasi masih kosong. Jadilah yang pertama!</div>}</section>;
 return <main className={`qw-shell ${done?'qw-show-ended':''}`}><div className="qw-ambience" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><nav className="qw-nav"><Link href="/" className="qw-brand"><img src="/branding/tekad-arcade-red.png" width="42" height="42" alt=""/><span>TEKAD <b>ARCADE</b></span></Link><div><button className="qw-small" aria-pressed={sound} onClick={()=>{setSound(!sound);if(!sound){try{audio.current=audio.current||new AudioContext();void audio.current.resume();}catch{}}}}>♪ {sound?'ON':'OFF'}</button><Link href="/">← Arcade</Link></div></nav>
 {error&&<div className="qw-error" role="alert"><span>{error}</span>{session.current&&<button onClick={()=>void send('sync')} disabled={busy}>Sambungkan ulang</button>}</div>}
 {boot?<section className="qw-loading"><div className="qw-orbit">◆</div><p>Menyambungkan panggung…</p></section>:!game?<><section className="qw-lobby"><div className="qw-lobby-copy"><span className="qw-kicker">SATU PEMAIN. LIMA SAHABAT. SATU PUNCAK.</span><h1 className="qw-logotype">SEJUTA<br/><em>POIN</em><span>TEKAD QUIZ SHOW</span></h1><p className="qw-lead">Seberapa jauh rasa ingin tahumu membawamu? Taklukkan 15 pertanyaan bersama TEKAD.</p><div className="qw-tags"><span>15 tingkat</span><span>4 pilihan</span><span>5 bantuan</span></div><form onSubmit={e=>{e.preventDefault();start();}}><label htmlFor="qw-name">Nama di leaderboard</label><input id="qw-name" autoComplete="nickname" placeholder="Nama panggilanmu" minLength={2} maxLength={24} required value={name} onChange={e=>setName(e.target.value)}/><button className="qw-primary" disabled={busy||name.trim().length<2||!key.current}>{busy?'Menyiapkan panggung…':'Masuk panggung →'}</button></form></div><div className="qw-poster"><div className="qw-orbit">◆</div><span className="qw-kicker">PUNCAK PENGETAHUAN</span><strong>1.000.000</strong><span>POIN · BUKAN HADIAH UANG</span><div className="qw-team">{HELPERS.map(h=><div key={h.id}><Portrait id={h.id}/><small>{h.name}</small></div>)}</div><p>Terpercaya · Eksploratif · Kolaboratif<br/>Adaptif · Determinasi</p></div></section><section className="qw-rules"><h2>Kenali tangganya</h2><div><article><b>01 / Kejar waktu</b><p>Tingkat 1–5: 15 detik, 6–10: 20 detik, 11–15: 25 detik. Waktu mulai saat soal dibuka dan tetap berjalan saat pindah tab.</p></article><article><b>02 / Amankan poin</b><p>Titik aman di tingkat 5 dan 10. Salah atau kehabisan waktu kembali ke titik aman. Pilih “Bawa pulang poin” untuk berhenti dengan skor saat ini.</p></article><article><b>03 / Gunakan bantuan</b><p>Setiap karakter membantu sekali. Pendapat Tim adalah voting simulasi dan bisa keliru. Baca penjelasan tanpa timer setelah setiap soal.</p></article></div></section>{leaderboard}</>:
 <><header className="qw-game-title"><div><span className="qw-kicker">TEKAD / SEJUTA POIN</span><h1>{done?'Panggungmu, pencapaianmu.':`Ayo, ${game.name}.`}</h1></div><div className="qw-score"><small>{done?'POIN AKHIR':'POIN TERKUMPUL'}</small><strong>{fmt(game.score)}</strong></div></header><div className="qw-journey" aria-label={`Progres: ${game.level} dari 15 soal benar`}><div><span>TINGKAT <b>{Math.min(15,game.level+(active?1:0))} / 15</b></span><span>MENUJU <b>1.000.000</b></span></div><ol aria-hidden="true">{POINTS.map((p,i)=><li key={p} className={`${i<game.level?'complete':''} ${active&&i===game.level?'now':''} ${i===4||i===9||i===14?'milestone':''}`}/>)}</ol></div><div className="qw-layout"><section className="qw-play">
 {game.phase==='ready'?<div className="qw-stage qw-ready"><span className="qw-kicker">PANGGUNG MILIKMU</span><div className="qw-team">{HELPERS.map(h=><Portrait key={h.id} id={h.id}/>)}</div><h2>Siap untuk pertanyaan pertama?</h2><p>15 detik untuk memilih dan mengunci jawaban. Bantuanmu siap di bawah. Timer dimulai saat soal dibuka.</p><button className="qw-primary" disabled={busy} onClick={()=>{beep(440);void send('next');}}>Buka soal pertama →</button></div>:<>
 {done&&<section className={`qw-finish ${game.result?.kind==='win'?'winner':''}`}><span className="qw-kicker">{game.result?.kind==='win'?'PUNCAK BERHASIL DITAKLUKKAN':'SETIAP LANGKAH MENAMBAH WAWASAN'}</span><div className="qw-finish-emblem" aria-hidden="true">{game.result?.kind==='win'?'✦':'◆'}</div><strong className="qw-final-points">{fmt(game.score)}<small>POIN</small></strong><h2>{({win:'Luar biasa. Kamu sampai puncak!',wrong:'Belum tepat. Tetap bertumbuh.',timeout:'Waktu habis.',walk:'Poinmu berhasil diamankan.'} as Record<string,string>)[game.result?.kind||'']}</h2><p>{game.level} dari 15 soal terjawab benar · {(game.elapsed/1000).toFixed(1)} detik total waktu menjawab.</p><button className="qw-primary" disabled={busy} onClick={()=>{session.current='';current.current=null;setGame(null);localStorage.removeItem('tekad-quiz-session');void board();}}>Main lagi →</button></section>}
 {q&&<section className={`qw-stage qw-question-stage ${success?'qw-success':''} ${done&&!success?'qw-settled':''} ${checkpoint?'qw-checkpoint':''}`}><div className="qw-stage-light" aria-hidden="true"/><div className="qw-question-top"><span>{q.category} <b>·</b> {['','Mudah','Menengah','Sulit'][q.tier]}</span>{active?<div className={`qw-clock ${remaining<=5?'urgent':''}`} role="timer" aria-label={`${Math.ceil(remaining)} detik tersisa`}>{Math.ceil(remaining)}<small>dtk</small></div>:<span className="qw-reveal-tag">PEMBAHASAN</span>}</div>{active&&<div className="qw-time-track" aria-hidden="true"><i style={{width:`${Math.min(100,remaining/q.duration*100)}%`}}/></div>}<span className="qw-kicker">{active?`SOAL ${game.level+1} / 15 · UNTUK ${fmt(POINTS[game.level])} POIN`:game.result?.kind==='correct'?'JAWABAN BENAR ✓':'PELAJARAN UNTUK LANGKAH BERIKUTNYA'}</span><h2>{q.text}</h2><div className="qw-answers">{q.options.map((o,i)=><button key={i} disabled={blocked||q.removed.includes(i)} aria-pressed={chosen===i} className={`${chosen===i?'selected':''} ${chosen===i&&pendingAction==='answer'?'locking':''} ${q.correct===i?'correct':''} ${q.correct!==undefined&&game.result?.chosen===i&&q.correct!==i?'wrong':''} ${q.removed.includes(i)?'removed':''}`} onClick={()=>{setChosen(i);beep(330);}}><span>{'ABCD'[i]}</span><b>{q.removed.includes(i)&&active?'—':o}</b>{q.vote&&active&&<small>{q.vote[i]}%</small>}</button>)}</div>
 {active&&<><div className="qw-help-result" aria-live="polite">{q.hint&&<p><b>Petunjuk Eldric:</b> {q.hint}</p>}{q.vote&&<p><b>Pendapat Tim:</b> voting simulasi, bukan jaminan jawaban benar.</p>}{q.second&&<p><b>Dylan siap:</b> satu kesempatan tambahan jika jawaban salah.</p>}{q.retried&&<p><b>Masih ada kesempatan!</b> Pilihan pertama belum tepat. Pilih lagi sebelum waktu habis.</p>}</div><button className="qw-primary qw-lock" disabled={blocked||chosen===null} onClick={()=>{beep(520);void send('answer',{choice:chosen});}}>{busy?'Memeriksa…':chosen===null?'Pilih jawaban di atas':`Kunci jawaban ${'ABCD'[chosen]} →`}</button></>}
 {q.explanation&&<div className="qw-explanation" aria-live="polite"><b>Kenapa {q.options[q.correct!]}?</b><p>{q.explanation}</p>{q.source?.url?<a href={q.source.url} target="_blank" rel="noreferrer">Sumber: {q.source.title} ↗</a>:<small>Penalaran: {q.source?.title}</small>}</div>}{game.phase==='review'&&<section className={`qw-decision ${checkpoint?'qw-checkpoint-decision':''}`}><span className="qw-kicker">{game.level===5||game.level===10?'◆ TITIK AMAN TERCAPAI':'LANGKAH BERIKUTNYA MILIKMU'}</span><h3>Lanjut naik atau amankan poin?</h3><div className="qw-decision-values"><div><small>Bawa pulang sekarang</small><strong>{fmt(game.score)}</strong></div><span>→</span><div><small>Target tingkat {game.level+1}</small><strong>{fmt(POINTS[game.level])}</strong></div></div><p>{game.score===game.safe?'Poinmu sudah berada di titik aman. Jika soal berikutnya salah, poin ini tetap kamu bawa.':`Jika salah atau waktu habis, skor kembali ke ${fmt(game.safe)} poin.`}</p><div className="qw-decision-actions"><button className="qw-primary" disabled={busy} onClick={()=>{beep(440);void send('next');}}>Lanjut · {fmt(POINTS[game.level])} poin →</button><button className="qw-small" disabled={busy} onClick={()=>dialog.current?.showModal()}>Amankan {fmt(game.score)} poin</button></div><small className="qw-decision-note">Ambil waktu untuk memutuskan. Timer soal berikutnya belum dimulai.</small></section>}</section>}
 </>}
 {!done&&<><section className="qw-helpers"><div className="qw-section-title"><h2>Sahabat TEKAD</h2><span>Sekali tiap karakter · +5 dtk</span></div><div className="qw-helper-grid">{HELPERS.map(h=><button key={h.id} disabled={busy||game.used.includes(h.id)||Boolean(active&&remaining<=0)} className={`${game.used.includes(h.id)?'used':''} ${helper===h.id?'selected':''}`} onClick={()=>setHelper(helper===h.id?null:h.id)} aria-label={`${h.name}: ${h.label}${game.used.includes(h.id)?', sudah dipakai':''}`}><Portrait id={h.id}/><strong>{h.name}</strong><small>{game.used.includes(h.id)?'Terpakai':h.label}</small></button>)}</div>{activeHelper&&cue&&<div key={`${game.id}:${cue.id}`} className="qw-helper-cue" role="status"><Portrait id={activeHelper.id}/><div><span className="qw-kicker">{activeHelper.name} MEMBANTU</span><strong>{helperMessages[activeHelper.id]}</strong><span className="qw-time-bonus">+5 detik</span></div></div>}{chosenHelper&&<div className="qw-helper-detail" key={chosenHelper.id}><Portrait id={chosenHelper.id}/><div><b>{chosenHelper.name} · {chosenHelper.label}</b><p>{chosenHelper.detail}</p></div>{active?<button disabled={blocked} onClick={()=>void send('help',{helper})}>Gunakan · +5 dtk</button>:<span>Siap saat soal dibuka</span>}</div>}</section><div className="qw-safety"><span>Titik aman <b>{fmt(game.safe)}</b></span><button className="qw-small" disabled={busy||Boolean(active&&remaining<=0)} onClick={()=>dialog.current?.showModal()}>Bawa pulang {fmt(game.score)} poin</button></div></>}
 </section><aside className="qw-desktop-ladder"><span className="qw-kicker">LANGKAH MENUJU PUNCAK</span>{ladder}<p>◆ Titik aman</p></aside></div><details className="qw-mobile-ladder"><summary>Lihat tangga poin <span>{fmt(game.score)} / 1.000.000</span></summary>{ladder}</details>{done&&leaderboard}</>}
 <footer className="qw-footer">SEJUTA POIN · TEKAD ARCADE</footer><dialog ref={dialog} className="qw-dialog"><h2>Amankan {fmt(game?.score||0)} poin?</h2><p>Permainan ini akan selesai. {active?'Timer tetap berjalan selama kamu memilih.':''}</p><button className="qw-primary" disabled={busy} onClick={()=>{dialog.current?.close();void send('walk');}}>Ya, bawa pulang poin</button><button className="qw-small" onClick={()=>dialog.current?.close()}>Kembali bermain</button></dialog>
 </main>;
}
